name: flutter_vm_v1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter_easyloading: ^3.0.0
  intl: ^0.17.0
  cached_network_image: ^3.1.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_app_name: ^0.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app-icon.png"

flutter_app_name:
  name: "Renyah-renyah"

flutter:
  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/images/
